import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/contexts/AuthContext";
import AuthButton from "@/components/AuthButton";
import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <header className="py-4 px-8 flex justify-between items-center border-b">
            <Link href="/">
              <span className="text-2xl font-bold">EventFinder</span>
            </Link>
            <nav className="flex items-center space-x-4">
              <Link href="/discover">
                <span className="text-gray-600 hover:text-gray-900">Discover</span>
              </Link>
              <AuthButton />
            </nav>
          </header>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
